// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWwwBeaqDk7kkI-1OBfkLLYfGN67LfEg4',
    appId: '1:207592702800:web:b1f12591833abcf282a255',
    messagingSenderId: '207592702800',
    projectId: 'wshieldtracking',
    authDomain: 'wshieldtracking.firebaseapp.com',
    storageBucket: 'wshieldtracking.firebasestorage.app',
    measurementId: 'G-N2WD1TZRCS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAigTAv66MlT_HOD8uZZd0FxAMQqJCDB6A',
    appId: '1:207592702800:android:63ea557885b6866e82a255',
    messagingSenderId: '207592702800',
    projectId: 'wshieldtracking',
    storageBucket: 'wshieldtracking.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzJFsf8Gx7L_PSXleOI8xeg10ulvAKGkQ',
    appId: '1:207592702800:ios:7ea6ffae0a7fc00c82a255',
    messagingSenderId: '207592702800',
    projectId: 'wshieldtracking',
    storageBucket: 'wshieldtracking.firebasestorage.app',
    iosBundleId: 'com.example.wshieldApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzJFsf8Gx7L_PSXleOI8xeg10ulvAKGkQ',
    appId: '1:207592702800:ios:7ea6ffae0a7fc00c82a255',
    messagingSenderId: '207592702800',
    projectId: 'wshieldtracking',
    storageBucket: 'wshieldtracking.firebasestorage.app',
    iosBundleId: 'com.example.wshieldApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWwwBeaqDk7kkI-1OBfkLLYfGN67LfEg4',
    appId: '1:207592702800:web:b34e411eea71b3be82a255',
    messagingSenderId: '207592702800',
    projectId: 'wshieldtracking',
    authDomain: 'wshieldtracking.firebaseapp.com',
    storageBucket: 'wshieldtracking.firebasestorage.app',
    measurementId: 'G-K6B5YVY2GS',
  );
}
